# Aufgabe 1
### Teil a
$$
M =
\begin{pmatrix}
1      & -1     & 0      & \cdots & 0      \\
-1     & 2      & \ddots & \ddots & \vdots \\
0      & \ddots & \ddots &        & 0      \\
\vdots & \ddots &        & 2      & -1     \\
0      & \cdots & 0      & -1     & 1      \\
\end{pmatrix}
$$

### Teil b 

In [1]:
function M(N)
    side = vcat(zeros(1,N), eye(N-1, N))
    diag = -2 * eye(N,N)
    diag[1,1] = -1
    diag[N,N] = -1
    return diag + side + side'
end

M (generic function with 1 method)

In [3]:
a = M(10)
a_ew = eigvals(a)
a_ev = eigvecs(a)
a_ew

10-element Array{Float64,1}:
 -3.90211   
 -3.61803   
 -3.17557   
 -2.61803   
 -2.0       
 -1.38197   
 -0.824429  
 -0.381966  
 -0.097887  
 -1.1143e-17

In [4]:
k = m = 1
omega = sqrt(k/m*abs(a_ew))
omega

10-element Array{Float64,1}:
 1.97538   
 1.90211   
 1.78201   
 1.61803   
 1.41421   
 1.17557   
 0.907981  
 0.618034  
 0.312869  
 3.33811e-9

In [8]:
zeros(1,6)

1×6 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0  0.0